-- Browser targets: display names, launching, and finding existing windows.
--
-- The target list is generated from local.browsers.targets into
-- generated/targets.lua. Nothing here may hard-code a profile: profile display
-- names are read from the browser's own Local State at runtime, which is what
-- keeps a client's name out of this public repo.

local M = {}

local whu = require("window-hotkey-utils")

local home = os.getenv("HOME") or ""

-- Where each Chromium browser keeps the directory -> display name mapping.
-- Browser knowledge, not client knowledge, so it stays in Lua rather than
-- inflating the nix option.
M.localState = {
  ["com.google.Chrome"] = home .. "/Library/Application Support/Google/Chrome/Local State",
  ["com.brave.Browser"] = home .. "/Library/Application Support/BraveSoftware/Brave-Browser/Local State",
  ["com.microsoft.edgemac"] = home .. "/Library/Application Support/Microsoft Edge/Local State",
  ["com.vivaldi.Vivaldi"] = home .. "/Library/Application Support/Vivaldi/Local State",
}

local ok, generated = pcall(require, "generated.targets")
M.targets = (ok and type(generated) == "table") and generated or {}

-- Loudly, because the degraded state is quiet and confusing: with no targets
-- the browser hotkeys bind nothing at all, and since Calendar has moved off c
-- three keys simply stop responding. Reachable while iterating, because the
-- hand-edited tree hot-reloads on any write and this file is generated by
-- build-switch.
if #M.targets == 0 then
  print("hammerspoon: no browser targets — generated/targets.lua is missing or empty; b/v/c will not bind")
end

-- ─── Profile display names ────────────────────────────────────────

-- Keyed by file path. Chromium rewrites Local State atomically (write to temp,
-- then rename), so a reader always sees a whole file and no locking is needed.
-- The previous value is kept and returned on any failure, so a browser that is
-- mid-write or a file that has been removed degrades to a stale name rather
-- than to none.
local cache = {}

local function readProfiles(path)
  local attr = hs.fs.attributes(path)
  local previous = cache[path] and cache[path].profiles
  if not attr or attr.mode ~= "file" then
    return previous
  end

  local key = tostring(attr.modification) .. "." .. tostring(attr.size)
  if cache[path] and cache[path].key == key then
    return cache[path].profiles
  end

  -- hs.json.read returns nil for every unreadable file; it only throws when
  -- handed a non-string, which cannot happen here.
  local decoded = hs.json.read(path)
  local info = type(decoded) == "table" and type(decoded.profile) == "table" and decoded.profile.info_cache
  if type(info) ~= "table" then
    return previous
  end

  local profiles = {}
  for dir, entry in pairs(info) do
    if type(entry) == "table" and type(entry.name) == "string" and entry.name ~= "" then
      profiles[dir] = { name = entry.name, gaia = entry.gaia_given_name }
    end
  end

  cache[path] = { key = key, profiles = profiles }
  return profiles
end

--- All known profiles for a bundle, how many there are, and whether the list
--- could be read at all.
---
--- The count matters because Chromium only appends a profile name to a window
--- title when it knows more than one profile. The third return matters because
--- a count of zero otherwise looks identical to a count of one: an unreadable
--- Local State, or a browser this file has no path for, would silently claim
--- that every window belongs to every profile.
function M.profiles(bundle)
  local path = M.localState[bundle]
  if not path then
    return {}, 0, false
  end
  local profiles = readProfiles(path)
  if not profiles then
    return {}, 0, false
  end
  local count = 0
  for _ in pairs(profiles) do
    count = count + 1
  end
  return profiles, count, true
end

--- Display name for a target's profile, and whether it was actually found.
function M.displayName(target)
  if not target.profileDir then
    return nil, false
  end
  local profiles = M.profiles(target.bundle)
  local entry = profiles[target.profileDir]
  if entry then
    return entry.name, true
  end
  return target.profileDir, false
end

--- Picker row text: the generic label, plus the real profile name when it can
--- be read. The label alone is what the repo knows; the name is runtime-only.
function M.label(target)
  local name, found = M.displayName(target)
  if not found or name == target.label then
    return target.label
  end
  return target.label .. " — " .. name
end

-- ─── Matching a window to a profile ───────────────────────────────

-- Chromium overrides the ACCESSIBLE window title (which is what hs.window
-- reads) in GetAccessibleWindowTitleForChannelAndProfile, appending the
-- browser name and then the profile's display name. That trailing name is
-- GetAvatarNameForProfile(), which for a signed-in profile is
-- "<GAIA given name> (<Local State name>)" — so matching the bare Local State
-- name finds nothing. Match both forms.
local function tailForms(entry)
  local forms = {}
  if entry and type(entry.name) == "string" and entry.name ~= "" then
    if type(entry.gaia) == "string" and entry.gaia ~= "" then
      forms[#forms + 1] = entry.gaia .. " (" .. entry.name .. ")"
      -- A signed-in profile still carrying Chrome's default local name shows
      -- the GAIA name alone.
      forms[#forms + 1] = entry.gaia
    end
    forms[#forms + 1] = entry.name
  end
  return forms
end

local function endsWithTail(title, tail)
  if #title <= #tail or title:sub(-#tail) ~= tail then
    return false
  end
  -- A page title could end in the same words by chance. Require a
  -- non-alphanumeric character before the tail; the separator itself is
  -- localized (en dash in de/fr/fi, "$1: $2" in pt-BR) so it cannot be matched
  -- literally.
  return title:sub(-#tail - 1, -#tail - 1):match("%w") == nil
end

--- Which profile directory a title belongs to, or nil when none matches.
---
--- Longest match wins. Display names are user-set, so one can be a suffix of
--- another — "Work" and "Client Work" — and testing only the target's own
--- tails would let the shorter name claim the longer profile's windows.
--- Deciding across all profiles at once is what makes a match unambiguous.
local function profileForTitle(profiles, title)
  -- Sorted, because pairs() order is undefined and this decides which browser
  -- a link is shown in: the same title must resolve to the same profile on
  -- every reload, and a tie must break the same way every time.
  local dirs = {}
  for dir in pairs(profiles) do
    dirs[#dirs + 1] = dir
  end
  table.sort(dirs)

  local bestDir, bestLen = nil, 0
  for _, dir in ipairs(dirs) do
    for _, tail in ipairs(tailForms(profiles[dir])) do
      if #tail > bestLen and endsWithTail(title, tail) then
        bestDir, bestLen = dir, #tail
      end
    end
  end
  return bestDir
end

--- Every window belonging to a target's profile.
---
--- Uses applicationsForBundleID, not application.get: an automation copy of
--- Chrome driven with its own --user-data-dir reports the same bundle id, and
--- get() returns only one of them.
local warned = {}

function M.windowsFor(target)
  local profiles, count, known = M.profiles(target.bundle)
  local matched = {}

  -- A profile was asked for on a browser whose Local State this file cannot
  -- find. Nothing can distinguish its windows, so they are all claimed — which
  -- is wrong as soon as two targets share the bundle. Say so once rather than
  -- letting two hotkeys quietly fight over one window.
  if target.profileDir and not known and not warned[target.bundle] then
    warned[target.bundle] = true
    print("hammerspoon: no Local State path for " .. target.bundle .. "; profiles cannot be told apart")
  end

  for _, app in ipairs(hs.application.applicationsForBundleID(target.bundle) or {}) do
    for _, win in ipairs(app:allWindows()) do
      -- app:allWindows() returns raw AX children and filters nothing: every
      -- Chromium window has a companion status-bar window, and those have no
      -- id and are never minimized. Left in, one of them gets picked as "the"
      -- window whenever the real one is minimized, and the hotkey goes dead.
      if win:isStandard() then
        if not target.profileDir or not known or count <= 1 then
          -- Nothing to distinguish: no profile asked for, no profile list
          -- readable, or the browser knows only one and so labels nothing.
          matched[#matched + 1] = win
        elseif profileForTitle(profiles, win:title() or "") == target.profileDir then
          matched[#matched + 1] = win
        end
      end
    end
  end

  return matched
end

-- ─── Launching ────────────────────────────────────────────────────

--- Open a URL, or the profile itself when url is nil.
---
--- -n is mandatory. --args maps to NSWorkspace's OpenConfiguration.arguments,
--- which applies "only when a new application instance is created", and -n is
--- what requests one. Without it LaunchServices reuses the running process,
--- argv is already fixed, and both the profile switch and the URL are dropped.
--- Chromium's own singleton then forwards the command line to the running
--- instance and the new copy exits, so this leaves no second process behind.
function M.launch(target, url)
  local args = {}

  -- -n belongs with --args and nowhere else: it is what creates the new
  -- instance --args applies to. On a launch that passes no switches it would
  -- instead force a genuine second copy of a browser that has no singleton to
  -- collapse it — Safari and Firefox declare no LSMultipleInstancesProhibited.
  if target.profileDir then
    args[#args + 1] = "-n"
  end

  local path = hs.application.pathForBundleID(target.bundle)
  if path then
    args[#args + 1] = "-a"
    args[#args + 1] = path
  else
    args[#args + 1] = "-b"
    args[#args + 1] = target.bundle
  end

  if target.profileDir then
    args[#args + 1] = "--args"
    args[#args + 1] = "--profile-directory=" .. target.profileDir
    if url then
      args[#args + 1] = url
    end
  elseif url then
    -- Deliberately NOT behind --args. open(1): everything after --args "is
    -- passed to the opened application in the argv parameter to main()" and is
    -- "not opened or interpreted by the open tool". Only Chromium parses a URL
    -- back out of its own argv, so for any other browser the link would
    -- silently vanish.
    args[#args + 1] = url
  end

  -- Absolute path: hs.task constructs happily from a bare command name but
  -- its :start() then returns false and nothing runs.
  local task = hs.task.new("/usr/bin/open", nil, args)
  return task ~= nil and task:start()
end

-- ─── Toggling ─────────────────────────────────────────────────────

-- Timers for windows that do not exist yet, held so they are not collected
-- before they fire. Keyed by target so a repeated press replaces rather than
-- stacks.
M._pending = {}

local function contains(windows, win)
  -- hs.window:id() is nil for a window whose AX id cannot be read, and
  -- Chromium has several such helper windows. Comparing two nils would report
  -- an unrelated window as this target's.
  local id = win and win:id()
  if not id then
    return false
  end
  for _, w in ipairs(windows) do
    if w:id() == id then
      return true
    end
  end
  return false
end

--- Focus this profile's window, or put it away if it already has focus.
---
--- app:hide() would take every profile of the same browser with it, so it is
--- used only when no other window of that application is visible. Otherwise
--- the window is minimized, which affects this profile alone.
function M.toggle(target, layoutFn)
  local windows = M.windowsFor(target)
  if #windows == 0 then
    -- Deliberately no setInputSource here, though whu.bindToggle does it on
    -- its launch path. Launching is asynchronous, so that call lands while the
    -- app the user is still typing in holds focus — one of the defects
    -- SYSMI-63 already tracks. Not worth reproducing in new code.
    M.launch(target, nil)

    -- The layout still has to be applied, as bindToggle did: the window does
    -- not exist yet, so it is positioned once the launch has produced one.
    -- The timer is held rather than discarded — hs.timer keeps no registry, so
    -- one referenced only by a local can be collected before it fires.
    if layoutFn then
      -- Replacing the slot is not enough: the old timer stays armed and would
      -- still fire, and its callback would clear the slot out from under the
      -- new one, dropping the module's only reference to it.
      local previous = M._pending[target.key]
      if previous then
        previous:stop()
      end
      local timer
      timer = hs.timer.doAfter(1.5, function()
        if M._pending[target.key] == timer then
          M._pending[target.key] = nil
        end
        local win = M.windowsFor(target)[1]
        if win then
          win:setFrame(layoutFn(whu.activeScreen(), win))
        end
      end)
      M._pending[target.key] = timer
    end
    return
  end

  local focused = hs.window.focusedWindow()
  if contains(windows, focused) then
    local app = focused:application()
    local othersVisible = false
    if app then
      for _, w in ipairs(app:visibleWindows()) do
        if not contains(windows, w) then
          othersVisible = true
          break
        end
      end
    end
    if app and not othersVisible then
      app:hide()
    else
      focused:minimize()
    end
    return
  end

  local win = windows[1]
  for _, w in ipairs(windows) do
    if w:isVisible() then
      win = w
      break
    end
  end

  local app = win:application()
  if app then
    app:unhide()
  end

  -- Restoring a minimized window is not optional: allWindows() counts
  -- minimized ones, so once this target's only window is in the Dock every
  -- later press would find it, skip the launch, and focus something the window
  -- server will not raise. The hotkey would go dead until the user clicked the
  -- Dock. win:focus() does not deminiaturize on its own.
  if win:isMinimized() then
    win:unminimize()
  end

  if layoutFn then
    win:setFrame(layoutFn(whu.activeScreen(), win))
  end
  win:focus()

  -- Matches what whu.bindToggle did for these keys before they moved here.
  whu.setInputSource(whu.fiProg)
end

return M
